### ISSUE TITLE
Create Warehouse Fails due to new parameter

### ISSUE THREAD

**Issue by sfc-gh-cdube** [Snowflake-Labs/terraform-provider-snowflake#1343]
**Provider Version**

v0.49.0

**Terraform Version**

>= 1.1.7

**Describe the bug**

When creating a ressource warehouse, the command passed to Snowflake adds the optional parameter query_acceleration_max_scale_factor, even though this is not a parameter in the ressource code. Since this is a parameter that needs enable_query_acceleration = True to works, this fails the statement. The Enable_query_acceleration is not even deployed in my region as we speak.

**Expected behavior**

Pass all of the default, which would pass the enable_query_acceleration to False, hence will not fail the statement.

**Comment by asnodgrass-nid** [comment]
```
│ Error: error altering warehouse: 001423 (22023): SQL compilation error:
│ invalid property 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'; feature 'Query Acceleration Service' not enabled
```

The workaround for me is to explicitly set `query_acceleration_max_scale_factor = 0` on all my `snowflake_warehouse` resources.

**Comment by sfc-gh-cdube** [comment]
I still needed to add enable_query_acceleration = False for it to work. and per documentation:
`Setting the QUERY_ACCELERATION_MAX_SCALE_FACTOR to 0 eliminates the limit and allows queries to lease as many resources as necessary and as available to service the query.`

**Comment by asnodgrass-nid** [comment]
It was enough in my case to just set that one property. The [PR](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1239) I found that added this change seems to set the boolean flag to `false` by default.

**Comment by asnodgrass-nid** [comment]
Given your region comment in the original post, it might be that a full workaround will vary depending on whether the preview is available in the target region.

**Comment by mnagaa** [comment]
I also encountered the same issue in the same provider version v0.49 of this thread, which caused failures in creating all warehouses. We currently use the standard edition for Snowflake. 
Perhaps, this came from the standard edition, but any warehouse without new accelerator features should be created for any edition.
If you find a workaround for this, please let me know.

The error case is as follows (with the standard edition):

```
resource "snowflake_warehouse" "XXX" {
  provider = snowflake.sys_admin
  name     = XXX
  comment  = "XXX"

  warehouse_size               = "small"
  auto_resume                  = true
  auto_suspend                 = 60
  statement_timeout_in_seconds = 3600
  initially_suspended          = true
  enable_query_acceleration    = false
}
```

**Comment by mnagaa** [comment]
Additionally, terraform plan shows following:

```
  # module.snowflake.snowflake_warehouse.query-small will be created
  + resource "snowflake_warehouse" "XXX" {
      + auto_resume                         = true
      + auto_suspend                        = 60
      + comment                             = "XXX"
      + enable_query_acceleration           = false
      + id                                  = (known after apply)
      + initially_suspended                 = true
      + max_cluster_count                   = (known after apply)
      + max_concurrency_level               = 8
      + min_cluster_count                   = (known after apply)
      + name                                = "XXX"
      + query_acceleration_max_scale_factor = 8
      + resource_monitor                    = (known after apply)
      + scaling_policy                      = (known after apply)
      + statement_queued_timeout_in_seconds = 0
      + statement_timeout_in_seconds        = 3600
      + warehouse_size                      = "small"
    }
```

**Comment by mnagaa** [comment]
As mentioned above, we could not create new warehouses. Today, our edition has been upgraded from standard to enterprise, the problem above was resolved for us.

**Comment by funes79** [comment]
should not this be closed as it has been fixed in 0.52? https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases/tag/v0.52.0

**Comment by asnodgrass-nid** [comment]
How does enabling some disabled tests relate to fixing the reported issue?

**Comment by belacevic** [comment]
We just updated to the provider version 0.54.0 (latest) and I can confirm the issue persists in all of the below-enterprise Snowflake accounts.

**Comment by belacevic** [comment]
The issue persists in v0.63, new warehouses are still (trying to be) created with the problematic parameter.

`terraform plan` shows the following:

```
  # snowflake_warehouse.read_user_wh["SOME_NAME"] will be created
  + resource "snowflake_warehouse" "read_user_wh"
      + auto_resume                         = (known after apply)
      + auto_suspend                        = 60
      + enable_query_acceleration           = false
      + id                                  = (known after apply)
      + initially_suspended                 = true
      + max_cluster_count                   = (known after apply)
      + max_concurrency_level               = 8
      + min_cluster_count                   = (known after apply)
      + name                                = "SOME_NAME_WH"
      + query_acceleration_max_scale_factor = 8
      + resource_monitor                    = (known after apply)
      + scaling_policy                      = (known after apply)
      + statement_queued_timeout_in_seconds = 0
      + statement_timeout_in_seconds        = 172800
      + warehouse_size                      = "xsmall"
      + warehouse_type                      = "STANDARD"
    }
```

While `terraform apply` causes the following error:

```
Error: error creating warehouse err = 001423 (22023): SQL compilation error:00:20
invalid property 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'; feature 'Query Acceleration Service' not enabled
```

**Comment by sfc-gh-ngaberel** [comment]
Hi all, this should be fixed by #1866, please continue the discussion in https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1628#issuecomment-1608440987 if the issue is still present after the next release (v0.67.1).

**Comment by AaronFriel** [comment]
@sfc-gh-ngaberel Is it possible to cut that v0.67.1 release? We at Pulumi have a mutual customer running into this:
- https://github.com/pulumi/pulumi-snowflake/issues/282

Would be great to see a regression test to keep this from being reintroduced again, as well.

**Comment by sfc-gh-ngaberel** [comment]
@AaronFriel this has been fixed (cf. https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1866) in v0.68 which I just released.
