### ISSUE TITLE
Provider trying to enable unavailable feature: Invalid Property QUERY_ACCELERATION_MAX_SCALE_FACTOR

### ISSUE THREAD

**Issue by DVAlexHiggs** [Snowflake-Labs/terraform-provider-snowflake#1628]
**Provider Version**

0.58.2 (I had this issue in 0.58.0 as well)

**Terraform Version**

1.4.0

**Describe the bug**

When creating a warehouse using Standard edition Snowflake, it tries to enable `QUERY_ACCELERATION_MAX_SCALE_FACTOR` which is unavailable in the Standard edition. It does this even with and without  ` enable_query_acceleration = false` in the resource definition.

**Expected behavior**

The warehouse should be created without trying to enable Query acceleration

**Code samples and commands**

With the following resource definitions:

```hcl
resource "snowflake_warehouse" "sandbox_warehouse_x_small" {
  name           = "SANDBOX_XS"
  comment        = "Warehouse for use in the developer SANDBOX Database"
  warehouse_size = "x-small"
  enable_query_acceleration = false
}
```

OR 

```hcl
resource "snowflake_warehouse" "sandbox_warehouse_x_small" {
  name           = "SANDBOX_XS"
  comment        = "Warehouse for use in the developer SANDBOX Database"
  warehouse_size = "x-small"
}
```

`terraform apply` produces the following error:

```shell
│ Error: error creating warehouse err = 001423 (22023): SQL compilation error:
│ invalid property 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'; feature 'Query Acceleration Service' not enabled
│ 
│   with snowflake_warehouse.sandbox_warehouse_x_small,
│   on warehouses.tf line 1, in resource "snowflake_warehouse" "sandbox_warehouse_x_small":
│    1: resource "snowflake_warehouse" "sandbox_warehouse_x_small" {
│ 
```
**Additional context**

- There is [an existing (merged) PR](https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1474) for this that seems to have identified the same issue and 'fixed' it. Someone on that thread does point out it is still a bug though

**Comment by sicarul** [comment]
I'm also having this exact issue indirectly using the Pulumi provider that wraps this library: https://github.com/pulumi/pulumi-snowflake

**Comment by philippeboyd** [comment]
Yes this is indeed a bummer... however, a workaround that I found working for me is adding the following 2 parameters in the warehouse resource and I'm then able to create a Warehouse even on a Standard Account
```
enable_query_acceleration = false
query_acceleration_max_scale_factor = 0
```

**Comment by PaulJulienRipoll** [comment]
Any updates on this? I can relate the exact same thing as @deivid-fatsecret said.

**Comment by bperkovic** [comment]
Same here with version 0.65, downgraded provider version to 0.63 that worked in past but now that one also doesnt work.

**Comment by vanducng** [comment]
current at 0.66.1 also still persists.

**Comment by bgabrhelik-com** [comment]
Furthermore the workaround above doesn't work for me in 0.66.1. I had to downgrade to 0.64.0
```
resource "snowflake_warehouse" "task_usage" {
  name = "TASK_PROCESSING"
  warehouse_size = var.processing_wh_size
  auto_resume = true
  auto_suspend = 300
  initially_suspended = true
  enable_query_acceleration = false
  query_acceleration_max_scale_factor = 0
  provider = snowflake.sys-admin
}
```

**Comment by clairemermet** [comment]
I confirm that the workaround doesn't work for version 0.66.1. Downgrade to 0.64.0 works.

**Comment by corrylc** [comment]
I am hitting this issue as well, and cannot create warehouses as a result. Any chance we can fix this breaking issue soon @sfc-gh-swinkler @sfc-gh-ngaberel?

**Comment by corrylc** [comment]
A workaround for the current provider version is to create the warehouse manually, then import it into Terraform.

**Comment by kulkarnisuraj92** [comment]
Stuck in a deadlock where getting this issue in 0.66.2 and older versions are resulting in #1868  not able to make complete deployment. Can we fix this issue soon?  @sfc-gh-swinkler  @sfc-gh-ngaberel

**Comment by philippeboyd** [comment]
@kulkarnisuraj92 FYI the `kind` bug should be fixed in the upcoming `0.67` release from PR #1880

**Comment by kulkarnisuraj92** [comment]
Thanks for the update @philippeboyd , will #1628 query acceleration bug will also be fixed in PR #1880? I was using 0.62 version without any issue but now 'kind' error is coming and in 0.66.2 'query acceleration' error is coming.

**Comment by sfc-gh-swinkler** [comment]
It looks like the default value for this is set to 8 https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/warehouse.go#L126. 

And then that default value is use to set the input config https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/warehouse.go#L171-L172. A simple fix would be to add an if/else block. 

i.e.

```
if !d.Get("enable_query_acceleration").(bool) {
 createOptions.QueryAccelerationMaxScaleFactor = sdk.Int(d.Get("query_acceleration_max_scale_factor").(int))
}
```
@sfc-gh-pbosak is this something you could take a look at?

**Comment by TCPIPStack** [comment]
I just upgraded to 0.67.0 hoping it would fix the bug, but I am still getting the same error with this config:

`resource "snowflake_warehouse" "airbyte" {
  name                                                  = local.airbyte_warehouse
  warehouse_size                                  = "xsmall"
  warehouse_type                                 = "STANDARD"
  enable_query_acceleration                 = false
  query_acceleration_max_scale_factor = 0
  auto_resume                                       = true
  auto_suspend                                      = 60
}`

**Comment by CrownBerry** [comment]
I prepared this PR weeks ago: #1866 
I hope it can fix this problem. What else should I do? Right now this PR is in the review stage but there are no comments.

**Comment by sfc-gh-ngaberel** [comment]
Thanks @CrownBerry, I've merged your PR which should fix this issue in the next release.

I've also created an issue in our internal system to add support and tests for the different account editions, so we can more easily support different SQL syntaxes in the future.

Closing this issue for now, don't hesitate to re-open if the issue is still present in the next release (probably v0.67.1).

**Comment by rjay98** [comment]
We're still seeing this issue in `0.68.2`!

**Comment by wh-k-klemens** [comment]
Issue also still present in `0.70.0`. Only fix is to downgrade to `0.64.0`

**Comment by sidharrth2002** [comment]
Bumping this up, we also face this issue in `0.68.0`, downgrading to `0.64.0` is a fix

**Comment by ameyapathare** [comment]
In version `0.84.1` we were also running into this, and we were able to get around it by setting the below on the warehouse resource
```
enable_query_acceleration           = false
query_acceleration_max_scale_factor = null
```

**Comment by nnnkkk7** [comment]
In version `0.94.0`, I hit this issue as well, but I got around it by this setting!
Thank you!

> In version `0.84.1` we were also running into this, and we were able to get around it by setting the below on the warehouse resource
> 
> ```
> enable_query_acceleration           = false
> query_acceleration_max_scale_factor = null
> ```

**Comment by Callumoco** [comment]
Confirmed this worked with Terraform version `1.0.8` and Snowflake provider version `0.99.0`.

Though we had to run the plan twice; the first time failed and showed the property changing `query_acceleration_max_scale_factor = 0 -> -1`. The second time we ran it it showed no change (`+ query_acceleration_max_scale_factor = 0`). It's almost like the initial plan does in fact change something but clearly not very visible to us 🤷‍♂ 

> In version `0.84.1` we were also running into this, and we were able to get around it by setting the below on the warehouse resource
> 
> ```
> enable_query_acceleration           = false
> query_acceleration_max_scale_factor = null
> ```

**Comment by NiklasRosenstein** [comment]
I've hit this snag today, it seems the provider wants to set it to a default value but then fails because it thinks the QAS feature must be enabled? Hit this after importing a warehouse that was created manually.

<img width="664" height="546" alt="Image" src="https://github.com/user-attachments/assets/c8da6dcc-cef6-4fd2-8e3f-12f36d33c6bb" />

Setting

```tf
  enable_query_acceleration           = false
  query_acceleration_max_scale_factor = 0
```

Explicitly did indeed fix it.
