### ISSUE TITLE
0.59.0 errors on snowflake_role_grants

### ISSUE THREAD

**Issue by bennylu2** [Snowflake-Labs/terraform-provider-snowflake#1642]
**Provider Version**

`0.59.0`

**Terraform Version**

`1.3.4`

**Describe the bug**

With `0.59.0` most grants have stopped crashing or erroring but we are seeing occasional errors with `snowflake_role_grants`; unexpected ID parts such as below

```
│ Error: unexpected number of ID parts (1), expected 6
│ 
│   with module.at_work_tracking.snowflake_role_grants.default,
│   on .terraform/modules/at_work_tracking/snowflake-user/roles.tf line 11, in resource "snowflake_role_grants" "default":
│   11: resource "snowflake_role_grants" "default" {
│ 
```

```
tf state show 'module.at_work_tracking.snowflake_role_grants.default'                                                                                                         
# module.at_work_tracking.snowflake_role_grants.default:
resource "snowflake_role_grants" "default" {
    id        = "AT_WORK_TRACKING"
    role_name = "AT_WORK_TRACKING"
    roles     = [
        "SYSADMIN",
    ]
    users     = [
        "SNOWFLAKE_AT_WORK_TRACKING_SRVC_RO",
    ]
}
```

**Expected behavior**

No error

**Comment by astanfel** [comment]
Was looking at this doing a compare with 0.56.2 and 0.59.0 in the docs and it looks like the identifier of the snowflake_role_grant has changed, can we allow for backwards compatibility? 

0.56.2 - https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.56.2/docs/resources/role_grants#import 

0.59.0 - https://registry.terraform.io/providers/Snowflake-Labs/snowflake/0.56.2/docs/resources/role_grants#import

**Comment by sfc-gh-swinkler** [comment]
Hello @bennylu2, thank you for bringing this to my attention. I will get this fixed ASAP.

**Comment by bennylu2** [comment]
@sfc-gh-swinkler in addition there's a bug with the `snowflake_pipe_grant` resource. It will always show a diff and want to add the role after apply so it has a perpetual diff

```
  # module.tdm_customers.module.private_raw.snowflake_pipe_grant.this["MONITOR"] will be updated in-place
  ~ resource "snowflake_pipe_grant" "this" {
        id                     = "TDM_CUSTOMERS|RAW||MONITOR|ANALYST,DMS_RO|false"
      ~ roles                  = [
          + "TDM_CUSTOMERS__RAW__READ",
        ]
        # (6 unchanged attributes hidden)
    }
```

**Comment by sfc-gh-swinkler** [comment]
Hello, i have a fix in 0.60, which solves both reported issues. Sorry it took a while, there were some unrelated build issues. Can you please confirm?

**Comment by bennylu2** [comment]
Looking preliminarily, the grant errors have been resolved but I am now seeing an issue with the resource monitor resource. I will open a separate bug for that

**Comment by saksham** [comment]
Thank you! Works nicely with version 0.60. 🙏

**Comment by thomassandslyst** [comment]
Hello. I'm still getting this error with 0.60 and 0.61 on all "snowflake_role_grants" coming from 0.56.3
