### ISSUE TITLE
err = missing destination name kind in *[]snowflake.Database

### ISSUE THREAD

**Issue by rjoelnorgren** [Snowflake-Labs/terraform-provider-snowflake#1868]
**Provider Version**

0.64

**Terraform Version**

1.4.6

**Describe the bug**
Snowflake [release 7.13 adds the kind column ](https://community.snowflake.com/s/article/SHOW-DATABASES-Command-New-Column-in-Output) to the show databases command. This behavior change was [enabled by default in the 7.19 release](https://community.snowflake.com/s/article/Pending-Behavior-Change-Log#disabled):
```sql
select current_version();
-- +-------------------+                                                           
-- | CURRENT_VERSION() |
-- |-------------------|
-- | 7.19.2            |
-- +-------------------+
```

I believe this is now causing the state refresh for our existing databases to fail:

```
Error: unable to scan row for SHOW DATABASES LIKE 'ANALYTICS' err = missing destination name kind in *[]snowflake.Database

  with snowflake_database.analytics,
  on databases.tf line 1, in resource "snowflake_database" "analytics":
   1: resource "snowflake_database" "analytics" {
```

**Expected behavior**

The state of the database refreshes successfully.

**Code samples and commands**

```
resource "snowflake_database" "analytics" {
  name                        = "ANALYTICS"
  data_retention_time_in_days = 14
  is_transient                = false
}
```

**Additional context**
A patch for this change would be appreciated. In particular, https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1845 is a major friction to us upgrading beyond 0.64.

**Comment by rjoelnorgren** [comment]
As a work around, we have disabled bundle 2023_03 which appears to have resolved the issue for now:
```sql
select system$disable_behavior_change_bundle('2023_03');
```

Assuming this is fixed in a release before the opt out period has ended, we ideally would prefer to not have to remove and re-import most of the role grants in our account from terraform state to upgrade (https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1845).

**Comment by jackwillisupside** [comment]
Hitting this same issue!

**Comment by walarue** [comment]
also hitting this, it's stopping our whole terraform configuration

**Comment by mcurtisslalom** [comment]
Hitting the same issue on 0.63

**Comment by yanlonghe** [comment]
Hitting the same issue on terraform: 1.4.6 and snowflake 0.64

**Comment by willwooten** [comment]
same issue 0.61

**Comment by skwon615** [comment]
I suspect the issue might be happening as early as v0.53.0 (based on [this PR](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1360)). I know basically nothing about Go, but seems like it's just because the `Database` struct doesn't have this new `kind` field: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/80488dae4e16f5c55f913449fc729fbd6e1fd6d2/pkg/snowflake/database.go#L254.

**Comment by willwooten** [comment]
> As a work around, we have disabled bundle 2023_03 which appears to have resolved the issue for now:
> 
> ```sql
> select system$disable_behavior_change_bundle('2023_03');
> ```
> 
> Assuming this is fixed in a release before the opt out period has ended, we ideally would prefer to not have to remove and re-import most of the role grants in our account from terraform state to upgrade (#1845).

this fix did not work for me. 

terraform plan does not recognize dbs exist. tries to create them. then apply fails.

**Comment by merlixo** [comment]
Same issue on 0.65

**Comment by astanfel** [comment]
This started effecting us today on 0.64

**Comment by sfc-gh-swinkler** [comment]
This was fixed in 0.66 as part of the databases SDK refactoring: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1840. Essentially the driver we were using was throwing an error when a field wasn't found in the scanned struct. We have changed that to not throw an error. If this field isn't found, it will just set it to an empty string. Furthermore, we did add "Kind" https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/sdk/databases.go#L571.

Please let me know after upgrading to 0.66 if this is still an issue and i would be happy to work with you to resolve it.

**Comment by willwooten** [comment]
i upgraded to 0.66.1 still not working. Everything was fine yesterday, stopped working today. terraform plan doesn't recognize dbs already exist.

**Comment by rjoelnorgren** [comment]
> This was fixed in 0.66 as part of the databases SDK refactoring: https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1840. Essentially the driver we were using was throwing an error when a field wasn't found in the scanned struct. We have changed that to not throw an error. If this field isn't found, it will just set it to an empty string. Furthermore, we did add "Kind" https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/sdk/databases.go#L571.
> 
> Please let me know after upgrading to 0.66 if this is still an issue and i would be happy to work with you to resolve it.

@sfc-gh-swinkler are there any plans to resolve #1845? This issue complicates upgrading from 0.64 to later versions.

**Comment by ppo-38** [comment]
Same in 0.64 and can't use 0.66 or higher for the moment because of #1845 which seems to remove all grants realized outside of terraform. So for the moment, we are totally blocked

**Comment by yuukiyamanaka** [comment]
> Same in 0.64 and can't use 0.66 or higher for the moment because of https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1845 which seems to remove all grants realized outside of terraform. So for the moment, we are totally blocked

I encounter the same problem.

**Comment by funes79** [comment]
Same issue here, 0.66.1 fixes the DBs visibility, but in the same time it wants to recreate **ALL** grants.

**Comment by attekei** [comment]
> Same in 0.64 and can't use 0.66 or higher for the moment because of #1845 which seems to remove all grants realized outside of terraform. So for the moment, we are totally blocked

Same same

**Comment by PaulJulienRipoll** [comment]
Isn't a Snowflake related problem? It worked perfectly until yesterday / today? Any support snowflake case news?

**Comment by willwooten** [comment]
We think that whatever the change was that caused the original issue deleted the dbs from the terraform state file when i ran 0.61.0. So after i updated to 0.66.1 that state file was already damaged / still thinks dbs dont exist when making plan

**Comment by Relativity74205** [comment]
> This was fixed in 0.66 as part of the databases SDK refactoring: #1840. Essentially the driver we were using was throwing an error when a field wasn't found in the scanned struct. We have changed that to not throw an error. If this field isn't found, it will just set it to an empty string. Furthermore, we did add "Kind" https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/sdk/databases.go#L571.
> 
> Please let me know after upgrading to 0.66 if this is still an issue and i would be happy to work with you to resolve it.

@sfc-gh-swinkler We also cannot upgrade to 0.66 as #1845 breaks our setup. Among other things, all the grants performed by AzureAD are dropped.

**Comment by walarue** [comment]
#1845 does make this really rough! We upgraded to 0.66.0, which does fix the error, but we are unable to manage any snowflake grants in terraform, because if we do any grants outside of terraform are revoked. Currently I'm working around this by using lifecycle blocks to ignore the users and roles lists in grant resources, but this definitely isn't workable outside of just inblocking my pipelines

**Comment by ppo-38** [comment]
Snowflake seems to have enabled bundle **2023_03** this week which is now in "opt-out period".

In this bundle, there is a change on the SHOW DATABASES command which has a new colmun named KIND (more info on [snowflake documentation](https://docs.snowflake.com/en/release-notes/bcr-bundles/2023_03/bcr-1021)).  I suppose that this change is at the origin of our problems.

For my part, I have disabled this bundle and trouble was solved for us.
Command to disable the bundle : `select SYSTEM$DISABLE_BEHAVIOR_CHANGE_BUNDLE('2023_03');`

Nevertheless, bundle will be enable by default in 2 months (without possibility to disable it) so I think that we will have to upgrade to a new release of the provider and for my part, I hope that issue #1845 will be solved...

**Comment by mlorek** [comment]
#1872 should fix  it

**Comment by natashamathur** [comment]
@walarue were you able to find a workaround for this? I'm hesitant to upgrade to 0.66.1 because our Terraform user itself was granted permission outside of terraform

**Comment by willwooten** [comment]
after i updated to 0.66 and cleaned the state file it worked but causes other problems with some of the grants

**Comment by toni-moreno** [comment]
In my current configuration we  don't use terraform to provision real users ( we have an Azure AD integration to automatically provision real users from the Azure AD ).

In this context, as a workaround to avoid removing users in the next `terraform apply`  I've changed my  `snowflake_role_grants` resource definition adding  `enable_multiple_grants = false ` and a ignore_changes for users in a lifecycle block

```
resource "snowflake_role_grants" "role_grant" {

  enable_multiple_grants = false
  role_name              = XXXX
  roles                  =  [ YYYY ]
  lifecycle {
    ignore_changes = [users]
  }

}
```

I hope this can help to other administrators in a similar context.  ( maybe won't be a good workaround if this terraform config is used also to provision  generic services users for external tooling connection, something I will need in the future)

**Comment by mcurtisslalom** [comment]
I second @toni-moreno comment above. Updating to version 0.66.2 along with ensuring the enabled_multiple_grants flag is declared in all grants worked for me. Note that I had some set to false and some set to true depending on the resource and it honored it either way.

**Comment by skwon615** [comment]
Hi @sfc-gh-swinkler - thanks for approving #1872. A common pain-point from this thread is that several teams (myself included) can't upgrade to version 0.65+ because of #1845. So if that issue won't be resolved soon, is it possible to release something like a v0.64.1 that just adds the change from #1872 into 0.64.0, so that teams can use their current provider versions in the meantime?

**Comment by erpel** [comment]
Thanks for confirming this works @susanneauxmoney , this opens up a path forward for us too.

**Comment by 65520** [comment]
We are facing the same issue in 0.63. Also, we cannot upgrade the version. Is there any workaround?
