### ISSUE TITLE
snowflake_file_format update-in-place doesn't apply

### ISSUE THREAD

**Issue by alexmaras** [Snowflake-Labs/terraform-provider-snowflake#2385]
### Terraform CLI and Provider Versions

```
Terraform v1.6.5
on linux_amd64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.82.0
```

### Terraform Configuration

```terraform
resource "snowflake_file_format" "csv" {
    binary_format                  = "HEX"
    compression                    = "AUTO"
    database                       = "RAW"
    date_format                    = "AUTO"
    empty_field_as_null            = true
    encoding                       = "UTF8"
    error_on_column_count_mismatch = true
    escape                         = "NONE"
    escape_unenclosed_field        = "NONE"
    field_delimiter                = ","
    field_optionally_enclosed_by   = "\""
    format_type                    = "CSV"
    id                             = "RAW|EXAMPLE_SCHEMA|PROCESS_CSV"
    name                           = "PROCESS_CSV"
    null_if                        = [
        "NULL",
    ]
    parse_header                   = false
    record_delimiter               = <<-EOT
        
    EOT
    replace_invalid_characters     = false
    schema                         = "EXAMPLE_SCHEMA"
    skip_blank_lines               = false
    skip_byte_order_mark           = true
    skip_header                    = 1
    time_format                    = "AUTO"
    timestamp_format               = "AUTO"
    trim_space                     = false
}
```

### Expected Behavior

Updating a field in the `file_format` resource and re-applying updates the file format in snowflake

### Actual Behavior

The update does not change anything in snowflake, and terraform picks up the change as needing to be applied every time

### Steps to Reproduce

1. Create a `snowflake_file_format` resource
2. `terraform apply`
3. Update the resource, change the `field_optionally_enclosed_by` field for instance (not specific to this field) to `NONE`
4. `terraform apply`

### How much impact is this issue causing?

Medium

### Additional Information

Workaround at the moment is to taint the resource in terraform and allow it to be destroyed and recreated.

**Comment by sfc-gh-asawicki** [comment]
Hey @alexmaras. Thanks for reporting the issue.

Could you provide the debug logs (`TF_LOG=DEBUG`) showing that the update is not taking place?

**Comment by justin-ramirez-gametime** [comment]
We are having a similar issue:
Terraform v1.7.0 on darwin_arm64
+ provider registry.terraform.io/snowflake-labs/snowflake v0.84.0

These are included on the plan every time:
![Screenshot 2024-01-22 at 1 45 46 PM](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/135072089/bc4fa298-428c-4e4d-8e0c-4eb5357afc3c)

However the state does not show any change after this plan is applied:
![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/135072089/1685df05-aa12-45a3-8e8d-0bf86d9bacd8)
![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/135072089/d09fdb2c-471f-4d78-b02b-3e37b90894f2)

To add to the complexity of this issue, this problem only persists in our staging and testing workspaces but not in Production. We speculated that this was because we imported these in production and the values were already set to true.

**Comment by alexmaras** [comment]
hi @sfc-gh-asawicki - thanks for the response. @justin-ramirez-gametime - the problem seems identical here. 

Attached are the logs from two applies that happened directly one after the other, both reporting success, with no change in snowflake. 

[tf-output.txt.gz](https://github.com/Snowflake-Labs/terraform-provider-snowflake/files/14017245/tf-output.txt.gz)
[tf-output-second.txt.gz](https://github.com/Snowflake-Labs/terraform-provider-snowflake/files/14017246/tf-output-second.txt.gz)

Here is the output from `terrafrom apply` too. 

[run-1.txt](https://github.com/Snowflake-Labs/terraform-provider-snowflake/files/14017261/run-1.txt)
[run-2.txt](https://github.com/Snowflake-Labs/terraform-provider-snowflake/files/14017262/run-2.txt)

**Comment by sfc-gh-asawicki** [comment]
Thanks for the logs @alexmaras, @justin-ramirez-gametime. I will analyze this issue this week.

**Comment by raulbonet** [comment]
Hello,

We had the same problem; I think I found the issue; created an MR with the fix.

**Comment by justin-ramirez-gametime** [comment]
Any news on this?

**Comment by sfc-gh-asawicki** [comment]
I have just merged the change @raulbonet mentioned in his previous comment. We plan to release the new version in the middle of the next week (Wednesday or Thursday).

**Comment by sfc-gh-asawicki** [comment]
@alexmaras @justin-ramirez-gametime the aforementioned PR was released as part of 0.86.0. Could you please check if this helps the issue for you?

**Comment by benriou** [comment]
hello

I'm still facing the same issue in 0.86.0 (tested today) where `escape_unenclosed_field` is always planned for update-in-place with no effect.

**Comment by raulbonet** [comment]
Hello @benriou 
Can you please post the terraform configuration and the plan so I can debug?

**Comment by benriou** [comment]
```

resource "snowflake_file_format" "loadbalancer_logs_XXX_dev" {
  name                = "LOADBALANCER_LOGS"
  database            = "DEV"
  schema              = "PUBLIC"
  format_type         = "CSV"
  binary_format       = "HEX"
  date_format         = "AUTO"
  time_format         = "AUTO"
  timestamp_format    = "AUTO"
  empty_field_as_null = true

  error_on_column_count_mismatch = true

  escape                  = "NONE"
  escape_unenclosed_field = "\\\\"
  encoding                = "UTF8"


  field_optionally_enclosed_by = "\""
  record_delimiter             = "\n"
  field_delimiter              = " "
  skip_header                  = 0
  skip_blank_lines             = true
  skip_byte_order_mark         = true
  null_if                      = ["\\\\N"]

  compression = "AUTO"
}
```


```
  # snowflake_file_format.loadbalancer_logs_XXX_dev will be updated in-place
  ~ resource "snowflake_file_format" "loadbalancer_logs_XXX_dev" {
      ~ escape_unenclosed_field        = "\\" -> "\\\\"
        id                             = "DEV|PUBLIC|LOADBALANCER_LOGS"
        name                           = "LOADBALANCER_LOGS"
        # (32 unchanged attributes hidden)
    }
```

**Comment by raulbonet** [comment]
Thanks, I will have a look later today

**Comment by benriou** [comment]
thank you @raulbonet  ; 

I thought I had to escape the backslashes. 

This is working like a charm since I configured the field to `\\` ; the change is correctly propagated to the FILE_FORMAT.

**Comment by raulbonet** [comment]
Glad to know it worked! :)

**Comment by sfc-gh-asawicki** [comment]
@alexmaras @justin-ramirez-gametime could you also confirm that it solved your issue, please?

**Comment by alexmaras** [comment]
thanks @sfc-gh-asawicki - I'll check it out tomorrow and report back.

**Comment by alexmaras** [comment]
Hey @sfc-gh-asawicki - The issue I'm hitting now is similar to the above, but I have no way of solving it. 

I have some file formats defined in Snowflake that have a character as their optional enclosing value - in this case double quotes (`"`). I need to change those file formats to have _no_ optional enclosing value - i.e. change it to `NONE`. If I use `NONE`, I now get an error - so this is an improvement - that says:

```
│ Error: CSVFieldOptionallyEnclosedBy must be one of [null ' "]
│ 
│   with module.ingest_seer_data["study_label_groups"].snowflake_file_format.csv[0],
│   on modules/snowpipe-integration/file_format.tf line 31, in resource "snowflake_file_format" "csv":
│   31: resource "snowflake_file_format" "csv" {
│ 
```

However, if I use `null`, terraform just doesn't report any changes at all. The file format _does_ need updating, but it refuses to plan it because it's using the defaults.

**Comment by raulbonet** [comment]
Thanks @alexmaras , I will have a look tomorrow (EMEA timezone)

**Comment by raulbonet** [comment]
Hello @alexmaras 
I had a look, and indeed you are right: the `validate()` should account for the `NONE` use-case. I am not sure if the intention of the original developer was to use `null` as `NONE` or indeed check for `null`, but the latter is not needed, since the validate function already has the condition `valueSet(opts.CSVFieldOptionallyEnclosedBy)`.

Anyway, I will create a PR with this small change.

**Comment by raulbonet** [comment]
@sfc-gh-asawicki , I notice a couple of issues here, just bringing it to your attention:

1. `NONE` is a Snowflake reserved keyword that afaik, currently the SQLBuilder does not support. So, the statement executed by Snowflake is:

`ALTER ...... = 'NONE'`, when it should be `ALTER ...... = NONE`

It seems that both seem to work in this case, but not sure if this is the case for absolutely all resources in Snowflake. 


2. I am noticing a non-idempotent operation here: if the resource is being created, Snowflake will default to whatever default value it has. However, if the resource is being altered, Snowflake will just keep the existing value. The only way to make this idempotent would be recreate the resource when a value is set to null, so it defaults to Snowflake's default value. 

I guess we do not want to address this in this PR, but this probably affects all resources. I wonder if we want to account for this use-case or at least track it in the backlog.

**Comment by sfc-gh-asawicki** [comment]
Hey @raulbonet. My answers below:

ad 1 
I will note it down, we should run it with `NONE`, not `'NONE'`.

ad 2
This is one of the topics we are aware of and that we will address during resources redesign (https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#our-roadmap). One of the PRs that shows how we can handle this is #2502. We are of course limited only to objects where we can easily access the default snowflake value. For the cases where this is not possible, we will just encourage the user to fill in the value (or even force the user to do it by requiring it).

**Comment by alexmaras** [comment]
Thanks @raulbonet for helping!

`0.87.1` has solved the issue, and I can apply file format updates successfully, including `"NONE"`!

![image](https://github.com/Snowflake-Labs/terraform-provider-snowflake/assets/7509232/b811e5f0-76ec-41a9-a1c5-6a39e0305f38)

Resolved by https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/2575 and released in `0.87.1`

**Comment by justin-ramirez-gametime** [comment]
@sfc-gh-asawicki version 0.87.1 fixed the issue we were having
