### ISSUE TITLE
[Bug]: Failed to revoke privileges to add for IMPORTED PRIVILEGES on SNOWFLAKE database

### ISSUE THREAD

**Issue by RobbertDM** [Snowflake-Labs/terraform-provider-snowflake#2803]
### Terraform CLI Version

1.3.8

### Terraform Provider Version

0.89

### Terraform Configuration

```terraform
locals {
  SNOWFLAKE_DATABASE_ACCESS_ROLES = [
    "SNOWFLAKE_INSPECTION"
  ]
}

# grant IMPORTED PRIVILEGES on SNOWFLAKE application
resource "snowflake_grant_privileges_to_account_role" "this" {
  for_each          = toset(local.SNOWFLAKE_DATABASE_ACCESS_ROLES)
  account_role_name = each.key
  privileges        = ["IMPORTED PRIVILEGES"]
  on_account_object {
    object_type = "DATABASE"
    object_name = "SNOWFLAKE"
  }
  with_grant_option = false
}
```

### Category

category:resource

### Expected Behavior

Use `snowflake_grant_privileges_to_account_role` to grant `IMPORTED PRIVILEGES` on the `SNOWFLAKE` database to some roles with `with_grant_option = false`.

### Actual Behavior

It gives an error when revoking the privilege.
```
Error: Failed to revoke privileges to add
│ 
│   with module.custom.snowflake_grant_privileges_to_account_role.this["SNOWFLAKE_INSPECTION"],
│   on ../../../../modules/snowflake/custom/snowflake_database_usage.tf line 17, in resource "snowflake_grant_privileges_to_account_role" "this":
│   17: resource "snowflake_grant_privileges_to_account_role" "this" {
│ 
│ Id: "SNOWFLAKE_INSPECTION"|false|false|IMPORTED PRIVILEGES|OnAccountObject|DATABASE|"SNOWFLAKE"
│ Privileges to add: [IMPORTED PRIVILEGES]
│ Error: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 24 unexpected 'IMPORTED'.
```

The SQL produced indeed is not valid, it produces:
`REVOKE GRANT OPTION FOR IMPORTED PRIVILEGES ON DATABASE "SNOWFLAKE" FROM ROLE "SNOWFLAKE_INSPECTION"`

instead what is correct is
`REVOKE IMPORTED PRIVILEGES ON DATABASE "SNOWFLAKE" FROM ROLE "SNOWFLAKE_INSPECTION"`

### Steps to Reproduce

run terraform apply on this, replacing the "SNOWFLAKE_INSPECTION" role with one that you have on your Snowflake account:

```
locals {
  SNOWFLAKE_DATABASE_ACCESS_ROLES = [
    "SNOWFLAKE_INSPECTION"
  ]
}

resource "snowflake_grant_privileges_to_account_role" "this" {
  for_each          = toset(local.SNOWFLAKE_DATABASE_ACCESS_ROLES)
  account_role_name = each.key
  privileges        = ["IMPORTED PRIVILEGES"]
  on_account_object {
    object_type = "DATABASE"
    object_name = "SNOWFLAKE"
  }
  with_grant_option = false
}
```

### How much impact is this issue causing?

Low

### Would you like to implement a fix?

- [ ] Yeah, I'll take it 😎

**Comment by RobbertDM** [comment]
I'm wondering whether you can give grant_options for IMPORTED PRIVILEGES?

**Comment by RobbertDM** [comment]
It seems like the concept of grant options is not relevant for `IMPORTED PRIVILEGES` ? 
Just in Snowflake, if I run
`GRANT IMPORTED PRIVILEGES ON DATABASE "SNOWFLAKE" TO ROLE "MY_ROLE" WITH GRANT OPTION;`
It gives me
`Syntax error: unexpected 'WITH'. (line 6)`

While 
`GRANT IMPORTED PRIVILEGES ON DATABASE "SNOWFLAKE" TO ROLE "MY_ROLE" ;`
works fine.

On another (non-shared) database, that syntax does actually work and sets the `grant_option` to true.

**Comment by sfc-gh-jcieslak** [comment]
Hey @RobbertDM 👋 
I believe the configuration should work with `object_type = "APPLICATION"` because Snowflake for show grants will return it as `APPLICATION` and not `DATABASE`. Regarding grant options, it's documented [here](https://docs.snowflake.com/en/sql-reference/sql/grant-privilege)(scroll to the `WITH GRANT OPTION` in the optional parameters section) and it says it's not possible to run with `IMPORTED PRIVILEGES`.

**Comment by RobbertDM** [comment]
Thanks for the quick answer @sfc-gh-jcieslak 

However, then it gives me
```
│ Error: expected on_account_object.0.object_type to be one of ["USER" "RESOURCE MONITOR" "WAREHOUSE" "COMPUTE POOL" "DATABASE" "INTEGRATION" "FAILOVER GROUP" "REPLICATION GROUP" "EXTERNAL VOLUME"], got APPLICATION
│ 
│   with module.custom.snowflake_grant_privileges_to_account_role.this,
│   on ../../../../modules/snowflake/custom/snowflake_database_usage.tf line 22, in resource "snowflake_grant_privileges_to_account_role" "this":
│   22:     object_type = "APPLICATION"
```

I am on Snowflake terraform provider 0.89, is this introduced later?

Also, we might want to update the main docs then, they mention `object_type = DATABASE`:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/docs/resources/grant_privileges_to_account_role.md?plain=1#L99

**Comment by RobbertDM** [comment]
Possibly relevant comment in the code:

https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/319ddc3df2f0a73c1f6258632de0e42c04532551/pkg/resources/grant_privileges_to_account_role.go#L812

**Comment by RobbertDM** [comment]
Ah, I think I found the one causing trouble:
https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/319ddc3df2f0a73c1f6258632de0e42c04532551/pkg/resources/grant_privileges_to_account_role.go#L529-L532

and specifically, line 531 sets `GrantOptionFor` to `true`.

As you mentioned before, `IMPORTED PRIVILEGES` does not have grant options.

So I think updates will always fail.

**Comment by sfc-gh-jcieslak** [comment]
Yeah, so my bad. The resource should be working with `object_type = "DATABASE"`, but it shouldn't have grant option enabled. I tested the following config with v0.89.0 and it worked and was created as well as destroyed without any errors:
```terraform
resource "snowflake_grant_privileges_to_account_role" "test" {
  account_role_name = "TEST_ROLE"
  privileges = [ "IMPORTED PRIVILEGES" ]
  on_account_object {
    object_type = "DATABASE"
    object_name = "SNOWFLAKE"
  }
  with_grant_option = false
}
```
It ran `REVOKE IMPORTED PRIVILEGES ON DATABASE "SNOWFLAKE" FROM ROLE "TEST_ROLE"`

**Comment by sfc-gh-jcieslak** [comment]
Hey @RobbertDM 👋 
Closing due to long inactivity and because similar issues (like [this one](https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/2366)) were already handled and confirmed the solution works in newer provider versions.

**Comment by xhensiladoda** [comment]
Actually this is not yet solved.
We are encountering the same issue and the provider version is 0.92.0

```
╷
│ Error: Failed to revoke privileges to add
│ 
│   with module.snowflake.snowflake_grant_privileges_to_account_role.grant_on_snowflake_database_to_datadog,
│   on modules/snowflake/grant_privileges_to_account_role.tf line 9, in resource "snowflake_grant_privileges_to_account_role" "grant_on_snowflake_database_to_datadog":
│    9: resource "snowflake_grant_privileges_to_account_role" "grant_on_snowflake_database_to_datadog" {
│ 
│ Id: "PROD_DATADOG"|false|false|IMPORTED
│ PRIVILEGES|OnAccountObject|DATABASE|"SNOWFLAKE"
│ Privileges to add: [IMPORTED PRIVILEGES]
│ Error: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 24 unexpected 'IMPORTED'.
```

This is our code definition:
```terraform
resource "snowflake_grant_privileges_to_account_role" "grant_on_snowflake_database_to_datadog" {
  account_role_name = snowflake_role.datadog.name
  privileges        = ["IMPORTED PRIVILEGES"]
  on_account_object {
    object_type = "DATABASE"
    object_name = "SNOWFLAKE"
  }
  with_grant_option = false
}
```
The code is applied successfully the first time, but then every time terraform runs again, the issue presents.

**Comment by sfc-gh-jcieslak** [comment]
Interesting, I'll reproduce the issue and get back to you.

**Comment by deanmorin** [comment]
I started seeing this issue in 0.92.0 as well, then upgraded to 0.95.0, where it was still happening.

I ended up manually running the revoke/grant statements for imported privileges which seems to have resolved it.

**Comment by sfc-gh-jcieslak** [comment]
Hey 👋 
I'm sorry, but I couldn't reproduce this error in any of the Terraform Provider versions. Maybe that's more connected to Snowflake than the provider itself. Please run the `terraform apply` with the `TF_LOG=DEBUG` environment variable set for more logging and post it here so I can check what SQLs are run (please be careful with sensitive data).

**Comment by martingehrke** [comment]
Here is the query being run that fails. My terraform is identical to the above.

```
REVOKE GRANT OPTION FOR IMPORTED PRIVILEGES ON DATABASE "DBNAME" FROM ROLE "DBNAME_READONLY"
```

**Comment by martingehrke** [comment]
> I started seeing this issue in 0.92.0 as well, then upgraded to 0.95.0, where it was still happening.
> 
> I ended up manually running the revoke/grant statements for imported privileges which seems to have resolved it.

what statements worked?

**Comment by sfc-gh-jmichalak** [comment]
Hi @martingehrke 👋 
I assume this happens during `terraform destroy`. I just tested @sfc-gh-jcieslak's configuration, and it works correctly on my side (apply, plan, destroy). What error do you get? Could you share logs with `TF_LOG=DEBUG`?

**Comment by kcd83** [comment]
Is only an issue on update when there is state drift?

```
terraform state show 'module.roles.module.roles["data_engineer"].module.databases.snowflake_gra
nt_privileges_to_account_role.grant["snowflake"]'
# module.roles.module.roles["data_engineer"].module.databases.snowflake_grant_privileges_to_account_role.grant["snowflake"]:
resource "snowflake_grant_privileges_to_account_role" "grant" {
    account_role_name = "DATA_ENGINEER"
    all_privileges    = false
    always_apply      = false
    id                = "\"DATA_ENGINEER\"|false|false|IMPORTED PRIVILEGES|OnAccountObject|DATABASE|\"SNOWFLAKE\""
    on_account        = false
    privileges        = [
        "IMPORTED PRIVILEGES",
    ]
    with_grant_option = false

    on_account_object {
        object_name = "SNOWFLAKE"
        object_type = "DATABASE"
    }
}
```

plan
```  # module.roles.module.roles["data_engineer"].module.databases.snowflake_grant_privileges_to_account_role.grant["snowflake"] will be updated in-place
  ~ resource "snowflake_grant_privileges_to_account_role" "grant" {
        id                = "\"DATA_ENGINEER\"|false|false|IMPORTED PRIVILEGES|OnAccountObject|DATABASE|\"SNOWFLAKE\""
      ~ privileges        = [
          + "IMPORTED PRIVILEGES",
        ]
        # (5 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
```
apply
```
╷
│ Error: Failed to revoke privileges to add
│ 
│   with module.roles.module.roles["data_engineer"].module.databases.snowflake_grant_privileges_to_account_role.grant["snowflake"],
│   on ../../modules/role/privileges/account/database/main.tf line 32, in resource "snowflake_grant_privileges_to_account_role" "grant":
│   32: resource "snowflake_grant_privileges_to_account_role" "grant" {
│ 
│ Id: "DATA_ENGINEER"|false|false|IMPORTED
│ PRIVILEGES|OnAccountObject|DATABASE|"SNOWFLAKE"
│ Privileges to add: [IMPORTED PRIVILEGES]
│ Error: 001003 (42000): SQL compilation error:
│ syntax error line 1 at position 24 unexpected 'IMPORTED'.
```
fix `terraform state rm 'module.roles.module.roles["data_engineer"].module.databases.snowflake_grant
_privileges_to_account_role.grant["snowflake"]'`

I.e recreating this this array of one with an update fails. Creating the new array of one works fine

I think the trick to repoducing this is to manually drop the privilege after applying it then attempting another apply

**Comment by mendhak** [comment]
I think this issue needs to be reopened, we ran into this situation just yesterday, pretty much same as [kcd83's comment](https://github.com/snowflakedb/terraform-provider-snowflake/issues/2803#issuecomment-3152992005). 

Terraform thinks it had granted IMPORTED PRIVILEGES to a role, and the state file showed as much.  
Reality did not agree, the Snowflake DB did not have anything granted for that role. 

Terraform _plan_ would notice it missing, and think that it needed to grant imported privileges to that role, but when applying, it was first trying to run an incorrect revoke statement.  

```sql
REVOKE GRANT OPTION FOR IMPORTED PRIVILEGES ON DATABASE "SNOWFLAKE" FROM ROLE "XXXXXXXXXXXXXXX" --terraform_provider_usage_tracking {"json_schema_version":"1","version":"v1.0.2","resource":"snowflake_grant_privileges_to_account_role","operation":"update"}
```

> SQL compilation error: syntax error line 1 at position 24 unexpected 'IMPORTED'.

So the terraform apply would keep failing here. 

In the end, our workaround was to manually grant the imported privileges with an account admin user:

```sql
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE "XXXXXXXXXXXXXXX";
```

**Comment by sfc-gh-jmichalak** [comment]
Hi @kcd83, @mendhak 👋 

We reproduced this. It looks like `IMPORTED PRIVILEGES` has a special behavior in Snowflake, and we need to adjust the resource behavior, although it looks like it's broken only during updating the resource. 

The workaround you provided is okay; the alternative is to recreate the resource with this privilege.
