### ISSUE TITLE
[General Usage]: Timeout Error When Creating Snowflake Database

### ISSUE THREAD

**Issue by mdelhaous** [Snowflake-Labs/terraform-provider-snowflake#3031]
### Terraform CLI Version

Terraform v1.4.2

### Terraform Provider Version

snowflake v0.25.0

### Terraform Configuration

```terraform
I'm encountering a timeout error when trying to create a Snowflake database using the Snowflake Terraform provider in a GitLab CI pipeline. The error indicates a timeout after 1 minute while attempting to create the database.

terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.25.0"  
    }
  }
}

provider "snowflake" {
  account  = var.snowflake_account
  username = var.snowflake_username
  password = var.snowflake_password
  role     = var.snowflake_role
}

resource "snowflake_database" "example_db" {
  name = var.database_name
}

output "database_name" {
  description = "The name of the Snowflake database"
  value       = snowflake_database.example_db.name
}
```

### Category

category:resource

### Object type(s)

resource:database

### Expected Behavior

I expected the Snowflake database to be created successfully without a timeout.

### Actual Behavior

The pipeline fails with a timeout error after 1 minute while attempting to create the Snowflake database.

### Steps to Reproduce

Copy the above Terraform configuration.
Run the pipeline in GitLab CI/CD.
Observe the timeout error in the terraform apply step.

### How much impact is this issue causing?

Low

**Comment by sfc-gh-asawicki** [comment]
Hey @mdelhaous. Thanks for reaching out to us.

You are using a really ancient version of the provider which is no longer supported. We recommend bumping (following our [migration guide](https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/MIGRATION_GUIDE.md#migration-guide) and you'll also need https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CZI_UPGRADE.md).

Because of the large version gap, it might be just easier to create an entirely new terraform deployment and import the existing objects.

**Comment by mdelhaous** [comment]
@sfc-gh-asawicki  Thank you so much for taking the time to respond! I really appreciate your help.

I've updated the code to the following:

**terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "0.36.0"
    }
  }
}**

However, I'm still encountering the same issue. Here’s the error I’m getting:

**Plan: 1 to add, 0 to change, 0 to destroy.
Changes to Outputs:
  + database_name = "example_db"
snowflake_database.example_db: Creating...
snowflake_database.example_db: Still creating... [10s elapsed]
snowflake_database.example_db: Still creating... [20s elapsed]
snowflake_database.example_db: Still creating... [30s elapsed]
snowflake_database.example_db: Still creating... [40s elapsed]
snowflake_database.example_db: Still creating... [50s elapsed]
╷
│ Error: error creating database: timeout after 1m0s. HTTP Status: 513. Hanging?
│ 
│   with snowflake_database.example_db,
│   on main.tf line 18, in resource "snowflake_database" "example_db":
│   18: resource "snowflake_database" "example_db" {
│ 
╵
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1**

If you have any further insights or suggestions, I'd greatly appreciate it!

I'm fairly new to Snowflake
Thanks again for your support.

**Comment by sfc-gh-asawicki** [comment]
Hey @mdelhaous, v0.36 was the first version of the provider under `"Snowflake-Labs/snowflake"`, but the current one is 0.94. It means you still have almost 60 minor versions to bump.

**Comment by mdelhaous** [comment]
Hello @sfc-gh-asawicki ,
im doing this :

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.94.1"
    }
  }
}

i still have the same error..

**Comment by sfc-gh-asawicki** [comment]
Hey @mdelhaous. It seems strange. Can you share the logs (you can run the terraform with `TF_LOG=DEBUG` environment variable)?

**Comment by mdelhaous** [comment]
hey @sfc-gh-asawicki  .. Sorry but i have another error now : 

**Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: open snowflake connection: Post "https://GGREFDS.CX82072.snowflakecomputing.com:443/session/v1/login-request?requestId=148d9e11-a889-4333-54d2-499f00551089&request_guid=c4643c4a-e44e-48f8-6012-566115e4058d": tls: failed to verify certificate: x509: certificate is valid for *.prod3.us-west-2.snowflakecomputing.com, *.us-west-2.snowflakecomputing.com, *.global.snowflakecomputing.com, *.snowflakecomputing.com, *.prod3.us-west-2.aws.snowflakecomputing.com, not GGREFDS.CX82072.snowflakecomputing.com
│
│   with provider["registry.terraform.io/snowflake-labs/snowflake"],
│   on main.tf line 10, in provider "snowflake":
│   10: provider "snowflake" {**

**Comment by sfc-gh-asawicki** [comment]
Hey @mdelhaous. Did you follow https://docs.snowflake.com/en/user-guide/admin-account-identifier#format-1-preferred-account-name-in-your-organization? It looks like your organization_name + account_name are not correct (please change it to the result of `SELECT CURRENT_ORGANIZATION_NAME() || '-' || CURRENT_ACCOUNT_NAME();`). Please let me know if this helps.

**Comment by mdelhaous** [comment]
Okey thank you @sfc-gh-asawicki  this is my code:

**variables.tf:**

# Snowflake provider configuration
variable "snowflake_account" {
  description = "The Snowflake account name"
  type        = string
  default     = "G****.C*****"
}

variable "snowflake_username" {
  description = "The Snowflake username"
  type        = string
  default     = "md****"
}

variable "snowflake_password" {
  description = "The Snowflake password"
  type        = string
  sensitive   = true
  default     = "Ima***"
}


variable "snowflake_role" {
  description = "The Snowflake role to use"
  type        = string
  default     = "ACCOUNTADMIN"
}

variable "snowflake_region" {
  description = "The Snowflake region"
  type        = string
  default     = "eu-west-2"
}

# Snowflake resources

variable "warehouse_name" {
  description = "The name of the Snowflake warehouse"
  type        = string
  default     = "example_warehouse"
}

**main.tf:**

terraform {
  required_providers {
    snowflake = {
      source  = "Snowflake-Labs/snowflake"
      version = "~> 0.94.1"
    }
  }
}

provider "snowflake" {
  account  = var.snowflake_account
  user = var.snowflake_username
  password = var.snowflake_password
  #role     = var.snowflake_role
  #region     = var.snowflake_region
}

# Create a Snowflake warehouse
resource "snowflake_warehouse" "example_warehouse" {
  name = var.warehouse_name
  warehouse_size = "SMALL"
}



it's right?

**Comment by sfc-gh-asawicki** [comment]
Hey. Please check https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/529#issuecomment-2328120943.

**Comment by mdelhaous** [comment]
Hey @sfc-gh-asawicki  ,

Thanks for the feedback! I’ve removed the region, updated the account to SELECT LOWER(current_organization_name() || '-' || current_account_name());, and checked the role assignment in the provider configuration. Everything is working perfectly now. Thank you so much for your help!

Thanks again! 🙌

**Comment by sfc-gh-asawicki** [comment]
Great to hear! Closing the ticket then.

**Comment by mdelhaous** [comment]
thanks @sfc-gh-asawicki
