### ISSUE TITLE
Unable to update share with new managed accounts

### ISSUE THREAD

**Issue by callumwebb** [Snowflake-Labs/terraform-provider-snowflake#555]
**Provider Version**

0.25.4

**Terraform Version**

v0.12.30

**Describe the bug**

I'm unable to add accounts to a `snowflake_share` after it has been created, if the share also has a usage grant on a database. I'm new to shares and managed accounts so it might be my own misunderstanding, but this could be a bug.

**Expected behavior**

I expected the share to be updated in-place, and this is what the plan suggests:
```
  # module.snowflake.snowflake_share.test will be updated in-place
  ~ resource "snowflake_share" "test" {
      ~ accounts = [
          - "XXXXXXX",
        ] -> (known after apply)
        id       = "TEST"
        name     = "TEST"
    }
```

**Code samples and commands**

I've stripped down my config to what I hope is the minimal set of resources to reproduce the issue. Note that my config is embedded inside a module (see the plan above), but hopefully this is unrelated. If I've stripped away too much and you're unable to reproduce the bug please let me know and I'll do some more work to isolate the issue!

```
locals {
  # the keys are account names, and the values are strings
  # that are meaningful in our environment
  reader_accounts =  {
    TEST = "test",
  }
}

resource "snowflake_managed_account" "reader" {
  for_each       = local.reader_accounts
  name           = each.key
  comment        = each.value 
  admin_name     = "admin"
  admin_password = "password" 
  type           = "READER"
}

resource "snowflake_database" "analytics" {
  name = "ANALYTICS"
}

resource "snowflake_share" "test" {
  name = "TEST"
  accounts = [
    for account in snowflake_managed_account.test :
    account.locator
  ]
}

resource "snowflake_database_grant" "analytics_usage" {
  database_name = snowflake_database.analytics.name
  privilege     = "USAGE"
  shares = [
    snowflake_share.test.name
  ]
}
```

The first plan / apply with this config succeeds. If I then add a new account by modifying `locals.reader_accounts`, e.g. like this:

```
locals {
  # the keys are account names, and the values are strings
  # that are meaningful in our environment
  reader_accounts =  {
    TEST = "test",
    ANOTHER = "another",
  }
}
```

I get the following error:

```
Error: error creating temporary DB grant TEMP_TEST_1622043816: 003033 (0A000): SQL compilation error:
Database 'TEMP_TEST_1622043816' does not belong to the database that is being shared.
```

**Additional context**

Checking the snowflake logs, immediately before the error a database is created `CREATE DATABASE "TEMP_TEST_1622043816"`, which succeeds.

I can't think of anything else, but please let me know if I can help by sharing any extra information! I appreciate all of the work being done on this provider 😄

**Comment by michal-rogalski** [comment]
Confirmed on Provider Version 0.25.18 Terraform Version v1.0.3
The issue happens when you are trying to update list of accounts and the share has USAGE permission on a database. 

**Root cause**:
The setAccounts function creates a temporary database and grants the USAGE privilege on the database to the share . The reason of the approach is described in the comment for the function: "There is a race condition where error accounts cannot be added to a share until after a database is added to the share. Since a database grant is dependent on the share itself, this is a hack to get the thing working".  

**Potential solution**
Maybe the better approach is separation of share creation and adding accounts to it. That will push the responsibility of the proper configuration to the developer.
This approach is also more natural, because in Snowflake you are using two commands: one "CREATE SHARE" and the second "ALTER SHARE ... SET ACCOUNTS ...".

**The workaround**
In my configuration I added execution of dynamically created SQL statements. 
One "REVOKE USAGE ON DATABASE ... FROM SHARE ..." before the snowflake_share resource and one with "GRANT USAGE ON DATABASE ... TO SHARE ..." after. Please be aware that this workaround my result in short term loss of access to data by the consumers.

**Comment by chrisluedtke** [comment]
This should be fixed in https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/762

**Comment by philkpler** [comment]
Hi there, is it OK ? I see the ticket still open...

**Comment by dmorel** [comment]
still an issue downstream in pulumi, so I suspect this isn't fixed (problem on share creation, bound to temporary database leading to "does not belong to the database that is being shared" errors. Slightly different scenario, but same root cause.

**Comment by Bryan-Meier** [comment]
This seems to be an issue in the 1.0.4 version of the provider. If it was working before which I suspect it was, it's now broke again.

**Comment by dsalaj** [comment]
We are experiencing this issue again in 2.1.0 version of the provider.

**Comment by sfc-gh-jcieslak** [comment]
Hello, I think this seems to be linked with https://github.com/snowflakedb/terraform-provider-snowflake/pull/4174#issuecomment-3674424651. As suggested there, let's create a new issue and not use closed threads for conversations.
